chore: Various improvements

diff --git a/bin/git-fresh-branch b/bin/git-fresh-branch
--- a/bin/git-fresh-branch
+++ b/bin/git-fresh-branch
@@ -2,19 +2,19 @@
 
 branch=$1
 
-test -z $branch && echo "branch required." 1>&2 && exit 1
+test -z "$branch" && echo "branch required." 1>&2 && exit 1
 
-changes=`git status --porcelain`
+changes=$(git status --porcelain)
 
 clean()
 {
-    git symbolic-ref HEAD refs/heads/$branch
+    git symbolic-ref HEAD "refs/heads/$branch"
     rm .git/index
     git clean -fdx
 }
 
-if [ ! -z "$changes" ]; then
-    read -p "All untracked changes will be lost. Continue [y/N]? " res
+if [ -n "$changes" ]; then
+    read -rp "All untracked changes will be lost. Continue [y/N]? " res
     case $res in
         [Yy]* ) ;;
         * ) exit 0;;
diff --git a/bin/git-rename-branch b/bin/git-rename-branch
--- a/bin/git-rename-branch
+++ b/bin/git-rename-branch
@@ -2,9 +2,9 @@
 set -e
 
 # Assert there is at least one branch provided
-test -z $1 && echo "new branch name required." 1>&2 && exit 1
+test -z "$1" && echo "new branch name required." 1>&2 && exit 1
 
-if [ -z $2 ]; then
+if [ -z "$2" ]; then
     new_branch="$1"
     old_branch="$(git symbolic-ref --short -q HEAD)"
 else
diff --git a/bin/git-rename-remote b/bin/git-rename-remote
--- a/bin/git-rename-remote
+++ b/bin/git-rename-remote
@@ -5,8 +5,8 @@ set -euo pipefail
 old=$1
 new=$2
 
-test -z $old && echo "old remote name required." 1>&2 && exit 1
-test -z $new && echo "new remote name required." 1>&2 && exit 1
+test -z "$old" && echo "old remote name required." 1>&2 && exit 1
+test -z "$new" && echo "new remote name required." 1>&2 && exit 1
 
 if ! git config --get "remote.$old.fetch" > /dev/null; then
   echo "remote $old doesn't exist"
@@ -14,7 +14,7 @@ if ! git config --get "remote.$old.fetch" > /dev/null; then
 fi
 
 if git config --get "remote.$new.fetch" > /dev/null; then
-  git remote remove $new
+  git remote remove "$new"
 fi
-git remote rename $old $new
+git remote rename "$old $new"
 git remote -v
