implements remote pref for create-branch

diff --git a/bin/git-create-branch b/bin/git-create-branch
--- a/bin/git-create-branch
+++ b/bin/git-create-branch
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 
+test $# -eq 0 && echo "branch argument required." 1>&2 && exit 1
+
 # preference takes lowest priority; look for remote from prefs first
 REMOTE_PREF=`git config git-extras.create-branch.remote`
-if [ ${REMOTE_PREF} == "true" ]; then
-	REMOTE=origin
-elif [ "$REMOTE_PREF" != ""]; then
+if [ -n "$REMOTE_PREF" ]; then
 	REMOTE=$REMOTE_PREF
 fi
 
@@ -26,17 +26,22 @@ do
 	shift
 done
 
+# handle ambiguous `-r` option argument by shift
 if [[ -z $BRANCH ]] && [[ -n $REMOTE ]]
 then
 	BRANCH=$REMOTE
 	REMOTE=origin
 fi
 
-test -z $BRANCH && echo "branch required." 1>&2 && exit 1
+test -z $BRANCH && echo "branch argument required." 1>&2 && exit 1
+
 if [[ -n $REMOTE ]]
 then
 	git ls-remote --exit-code $REMOTE 1>/dev/null 2>/tmp/ls-remote-error
-	if [ $? = 0 ]
+	REMOTE_EXIT=$?
+	REMOTE_ERROR=$(</tmp/ls-remote-error)
+	rm -f /tmp/ls-remote-error
+	if [ $REMOTE_EXIT -eq 0 ]
 	then
 		git push $REMOTE HEAD:refs/heads/$BRANCH
 		git fetch $REMOTE
@@ -44,8 +49,9 @@ then
 		exit $?
 	else
 		echo
-		echo "    Error connecting to remote '$REMOTE': `cat /tmp/ls-remote-error`"
-		rm -f /tmp/ls-remote-error
+		echo "    Error connecting to remote '$REMOTE': $REMOTE_ERROR"
+		echo
+		exit $REMOTE_EXIT
 	fi
 fi
 
