Remove unnecessary check

diff --git a/bin/git-force-clone b/bin/git-force-clone
--- a/bin/git-force-clone
+++ b/bin/git-force-clone
@@ -46,11 +46,9 @@ main() {
         exit 0
         ;;
       * )
-        if [[ "${1:0:1}" == '-' ]]; then
-          echo "Error: Invalid option: $1"  >>/dev/stderr
-          _usage
-          exit 1
-        fi
+        echo "Error: Invalid option: $1"  >>/dev/stderr
+        _usage
+        exit 1
         ;;
     esac
     shift
