Address issue #190, git-setup should test for existing .git in target directory
- now exits with an error message if the target directory already has a .git directory

diff --git a/bin/git-setup b/bin/git-setup
--- a/bin/git-setup
+++ b/bin/git-setup
@@ -1,8 +1,16 @@
 #!/bin/sh
 
+gitdirexists(){
+    if [ -d ".git" ]; then
+        echo ".git directory already exists, aborting"
+        exit 1
+    fi
+}
+
 dir=$(test -z "$*" && echo "." || echo "$*")
 mkdir -p "$dir" \
   && cd "$dir" \
+  && gitdirexists \
   && git init \
   && git add . \
   && git commit -m 'Initial commit'
