reauthor: remove use of getopt to parse options
- difference of behavior between BSD getopt (comes on Mac) and GNU getopt
- getopts doesn't support long option names
=> manual parsing

diff --git a/bin/git-reauthor b/bin/git-reauthor
--- a/bin/git-reauthor
+++ b/bin/git-reauthor
@@ -71,29 +71,43 @@ reauthor() {
 
 
 parse_options() {
-  OPTIONS=$(
-    getopt \
-    --options ACe:hn:o:t: \
-    --longoptions 'all,config,correct-email:,correct-name:,old-email:,type:' \
-    --name "${COMMAND}" \
-    -- "$@"
-  )
-
-  [[ $? -eq 0 ]] || error
-
-  eval set -- "${OPTIONS}"
-
   while [[ "$#" -gt 0 ]]; do
     case "$1" in
-      --all|-A) ALL=true; shift ;;
-      --config|-C) CONFIG=true; shift ;;
-      --correct-email|-e) CORRECT_EMAIL="$2"; shift 2 ;;
-      -h) usage; exit 0 ;;
-      --correct-name|-n) CORRECT_NAME="$2"; shift 2 ;;
-      --old-email|-o) OLD_EMAIL="$2"; shift 2 ;;
-      --type|-t) TYPE="$2"; shift 2 ;;
-      --) shift ;;
-      *) error "invalid option '$1'" ;;
+      --all|-A)
+        ALL=true
+        shift
+        ;;
+      --config|-C)
+        CONFIG=true
+        shift
+        ;;
+      --correct-email|-e)
+        [[ -n "${2+x}" ]] || error 'Missing correct-email value'
+        CORRECT_EMAIL="$2"
+        shift 2
+        ;;
+      -h)
+        usage
+        exit 0
+        ;;
+      --correct-name|-n)
+        [[ -n "${2+x}" ]] || error 'Missing correct-name value'
+        CORRECT_NAME="$2"
+        shift 2
+        ;;
+      --old-email|-o)
+        [[ -n "${2+x}" ]] || error 'Missing old-email value'
+        OLD_EMAIL="$2"
+        shift 2
+        ;;
+      --type|-t)
+        [[ -n "${2+x}" ]] || error 'Missing type value'
+        TYPE="$2"
+        shift 2
+        ;;
+      *)
+        error "invalid option '$1'"
+        ;;
     esac
   done
 
