reauthor: use command-line named options

diff --git a/bin/git-reauthor b/bin/git-reauthor
--- a/bin/git-reauthor
+++ b/bin/git-reauthor
@@ -1,10 +1,19 @@
 #!/usr/bin/env bash
 
-export OLD_EMAIL="$1"
-export CORRECT_EMAIL="$2"
-export CORRECT_NAME="$3"
+OLD_EMAIL=
+CORRECT_EMAIL=
+CORRECT_NAME=
+
+error() {
+  [[ -z "$1" ]] || echo "error: $1" >&2
+  exit 1
+}
 
 reauthor() {
+  export OLD_EMAIL
+  export CORRECT_EMAIL
+  export CORRECT_NAME
+
   git filter-branch -f --env-filter '
     if [ "${GIT_AUTHOR_EMAIL}" = "${OLD_EMAIL}" ]; then
       export GIT_AUTHOR_EMAIL="${CORRECT_EMAIL}"
@@ -17,5 +26,31 @@ reauthor() {
     fi
   ' --tag-name-filter cat -- --branches --tags
 }
+
+OPTIONS=$(
+  getopt \
+  --options e:n:o: \
+  --longoptions 'correct-email:,correct-name:,old-email:' \
+  --name reauthor \
+  -- "$@"
+)
+
+[[ $? -eq 0 ]] || error
+
+eval set -- "${OPTIONS}"
+
+while [[ "$#" -gt 0 ]]; do
+  case "$1" in
+    --correct-email|-e) CORRECT_EMAIL="$2"; shift 2 ;;
+    --correct-name|-n) CORRECT_NAME="$2"; shift 2 ;;
+    --old-email|-o) OLD_EMAIL="$2"; shift 2 ;;
+    --) shift ;;
+    *) error "invalid option '$1'" ;;
+  esac
+done
+
+[[ -n "${OLD_EMAIL}" ]] || error "missing required old-email option"
+[[ -n "${CORRECT_EMAIL}" ]] || error "missing required correct-email option"
+[[ -n "${CORRECT_NAME}" ]] ||  error "missing required correct-name option"
 
 reauthor
