Significant update to bin/git-feature
- Changed option parsing so that `--alias` requires an argument and will
  fail with an error unless provided. Applied the same logic to
  `--separator`.

- Changed `finish` parsing to capture it as a variable flag during
  argument parsing.

  This could be extended so that if `finish` is already true, a second
  `finish` results in the word being added to the argument list.

  ```console
  $ git feature -- finish remote
  $ git feature finish finish remote
  ```

  This has not been done because it is a bit of an inconsistent handling
  for documentation purposes.

- Add handling of `--` to permit options or `finish` to be made part of
  the feature branch name.

- Since `finish` is now a variable flag, simplify the name-building
  logic to always use `concatargs "${argv[@]}"`. This means that
  `git feature finish ...` and `git feature ...` behave the same in
  terms of feature branch name building.

- Basically rewrote the man page to include better descriptions of the
  options as well as adding a GIT CONFIG section and additional EXAMPLES
  for the new features/behaviour.

diff --git a/bin/git-feature b/bin/git-feature
--- a/bin/git-feature
+++ b/bin/git-feature
@@ -13,21 +13,23 @@ if [ -z "$branch_separator" ]; then
 fi
 
 merge_mode="--no-ff"
+finish=false
 declare -a argv
 while test $# != 0
 do
   case $1 in
   -a|--alias )
-    if [[ -n $2 ]]
+    if [[ -n $2 ]] && [[ $2 != -- ]]
     then
       shift # shift -a|-alias
       branch_prefix=$1
     else
-      argv+=("$1") # treat tail '-a' as <name>
+      echo >&2 "option $1 requires a value"
+      exit 1
     fi
     ;;
   -r|--remote )
-    if [[ -n $2 ]]
+    if [[ -n $2 ]] && [[ $2 != -- ]]
     then
       remote=$2
       shift
@@ -36,12 +38,13 @@ do
     fi
     ;;
   -s|--separator )
-    if [[ -n $2 ]]
+    if [[ -n $2 ]] && [[ $2 != -- ]]
     then
       branch_separator=$2
       shift
     else
-      argv+=("$1") # treat tail '-s' as <name>
+      echo >&2 "option $1 requires a value"
+      exit 1
     fi
     ;;
   --squash )
@@ -50,6 +53,15 @@ do
   --from )
     start_point=$2
     shift
+    ;;
+  -- )
+    # terminate argument parsing
+    shift
+    argv+=("$@")
+    break
+    ;;
+  finish )
+    finish=true
     ;;
   * )
     argv+=("$1")
@@ -63,18 +75,14 @@ concatargs() {
   branch="$branch_prefix$branch_separator$str"
 }
 
-if test "${argv[0]}" = "finish"; then
-  test -z "${argv[1]}" && echo "$branch_prefix" "<name> required." 1>&2 && exit 1
-  branch="$branch_prefix$branch_separator${argv[1]}"
+test -z "${argv[0]}" && echo "$branch_prefix" "<name> required." 1>&2 && exit 1
+
+concatargs "${argv[@]}"
+
+if "${finish}"
+then
   git merge ${merge_mode} "$branch" && git delete-branch "$branch"
 else
-  test -z "${argv[0]}" && echo "$branch_prefix" "<name> required." 1>&2 && exit 1
-  if test -n "${argv[1]}"; then
-    concatargs "${argv[@]}"
-  else
-    branch="$branch_prefix$branch_separator${argv[0]}"
-  fi
-
   if [[ -n $remote ]] && [[ -z $start_point ]]
   then
     git create-branch -r "$remote" "$branch"
