chore: Fix more Bash inconsistencies

diff --git a/bin/git-stamp b/bin/git-stamp
--- a/bin/git-stamp
+++ b/bin/git-stamp
@@ -22,8 +22,7 @@ EOF
 
 error() {
   if [[ -n "$1" ]]; then
-    local msg=$( echo "error: $1" )
-    echo -e "${msg}" >&2
+    echo "error: $1" >&2
   fi
   usage
   exit 1
