git-pr: accpeted multiple GitHub URL or ID with remote.

diff --git a/bin/git-pr b/bin/git-pr
--- a/bin/git-pr
+++ b/bin/git-pr
@@ -11,28 +11,45 @@ pull() {
   git config --local --replace branch.$branch.remote $remote;
 }
 
+pull_pr_if_matched() {
+  if [[ $1 =~ ^(.*):([0-9]+)|(https?://[^/]+/.+)/pull/([0-9]+).*$ ]]; then
+    if [[ -n ${BASH_REMATCH[2]} ]]; then
+        remote="${BASH_REMATCH[1]:-origin}"
+        id="${BASH_REMATCH[2]}"
+    else
+        remote="${BASH_REMATCH[3]}.git"
+        id="${BASH_REMATCH[4]}"
+    fi
+
+    branch=pr/$id
+    pull "$remote" "$id" "$branch"
+    return $?
+  fi
+
+  echo "$1 doesn't match the pr id pattern."
+  return 1
+}
+
+test -z "$1" && echo "pr number required." 1>&2 && exit 1
+
 if test "$1" = "clean"; then
   git for-each-ref refs/heads/pr/* --format='%(refname)' | while read ref; do
     git branch -D ${ref#refs/heads/}
   done
-  exit 0
 
-elif [[ $1 =~ ^(.*):([0-9]+)|(https?://[^/]+/.+)/pull/([0-9]+).*$ ]]; then
-  if [[ -n ${BASH_REMATCH[2]} ]]; then
-    remote="${BASH_REMATCH[1]:-origin}"
-    id="${BASH_REMATCH[2]}"
-  else
-    remote="${BASH_REMATCH[3]}.git"
-    id="${BASH_REMATCH[4]}"
-  fi
-
-  branch=pr/$id
-  pull "$remote" "$id" "$branch"
-
-else
-  test -z $1 && echo "pr number required." 1>&2 && exit 1
+elif [[ "$1" =~ ^[0-9]+$ ]]; then
   remote=${2:-origin}
   id=$1
   branch=pr/$id
   pull "$remote" "$id" "$branch"
+
+else
+  rc=1
+  while [ "$1" != "" ]; do
+    pull_pr_if_matched "$1"
+    rc=$?
+    shift
+  done
+
+  exit "$rc"
 fi
